[package]
name = "nuttx_rs"
version = "0.1.0"
authors = ["Huang Qi <huangqi3@xiaomi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
num_cpus = "1.0"