[package]
name = "nuttx_rs"
version = "0.1.0"
authors = ["Huang Qi <huangqi3@xiaomi.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
