name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        repository: apache/incubator-nuttx
        path: nx/nuttx
    - uses: actions/checkout@v2
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        repository: apache/incubator-nuttx-apps
        path: nx/apps
    - run: find nx -name defconfig | xargs sed -i 's/nsh_main/main/g'
    - name: Cache NuttX
      uses: actions/cache@v2
      id: cache
      with:
        key: apache-nuttx-source
        path: |
          nx/apps
          nx/nuttx

  Build_for_ARM:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - run: rustup target add thumbv7m-none-eabi
    - run: rustup target add thumbv7em-none-eabi
    - run: rustup target add thumbv7em-none-eabihf
    - run: rustup target add thumbv8m.base-none-eabi
    - run: rustup target add thumbv8m.main-none-eabi
    - run: rustup target add thumbv8m.main-none-eabihf
    - run: cargo build --target=thumbv7m-none-eabi
    - run: cargo build --target=thumbv7em-none-eabi
    - run: cargo build --target=thumbv7em-none-eabihf
    - run: cargo build --target=thumbv8m.base-none-eabi
    - run: cargo build --target=thumbv8m.main-none-eabi
    - run: cargo build --target=thumbv8m.main-none-eabihf

  Build_for_RISCV:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - run: rustup target add riscv32i-unknown-none-elf
    - run: rustup target add riscv32imc-unknown-none-elf
    - run: rustup target add riscv32imac-unknown-none-elf
    - run: rustup target add riscv64imac-unknown-none-elf
    - run: rustup target add riscv64gc-unknown-none-elf
    - run: cargo build --target=riscv32i-unknown-none-elf
    - run: cargo build --target=riscv32imc-unknown-none-elf
    - run: cargo build --target=riscv32imac-unknown-none-elf
    - run: cargo build --target=riscv64imac-unknown-none-elf
    - run: cargo build --target=riscv64gc-unknown-none-elf

  Build_for_Examples:
    runs-on: ubuntu-latest
    needs: Fetch
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - run: rustup target add thumbv7em-none-eabihf
    - name: Install build toolkit
      run: sudo apt install -y gcc-arm-none-eabi kconfig-frontends
    - name: Build
      run: NUTTX_SRC_DIR=$PWD/nx/nuttx cargo build --example helloworld --target=thumbv7em-none-eabihf